# Generated by Django 4.2.14 on 2025-09-30 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=10, unique=True, verbose_name='DNI/Cédula')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], default='M', max_length=1)),
                ('ciudad', models.CharField(choices=[('MDE', 'Medellín'), ('BOG', 'Bogotá'), ('CAL', 'Cali'), ('BCN', 'Barcelona'), ('UIO', 'Quito'), ('GYE', 'Guayaquil')], default='MDE', max_length=3)),
            ],
            options={
                'verbose_name_plural': 'Personas',
                'ordering': ['apellidos'],
            },
        ),
    ]
